url:
name: Iruka Bando
icon: /assets/head.png
lead:
desc:
items:
- name: Home
  href: /
links:
- name: Twitter
  href: https://twitter.com/sendaiperson
  icon: fab fa-twitter
- name: Iruka Bando
  href: 
jumps:
- name: GitHub
  href: 
  icon: fab fa-github
- name: Issues
  href: 
  icon: fas fa-comments
nomath: false
google_analytics:
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
